name: ğŸš€ Deploy Endatix Hub

on:
  workflow_dispatch:

jobs:
  deploy-endatix-hub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
        - name: ğŸ” Checkout code
          uses: actions/checkout@v4

        - name: ğŸ“¦ Setup pnpm
          uses: pnpm/action-setup@v4
          with:
            version: 10.10
            run_install: false

        - name: ğŸ“¦ Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20.9.0
            cache: 'pnpm'
            cache-dependency-path: ./pnpm-lock.yaml

        - name: ğŸ¥¡ Install Dependencies
          shell: bash
          working-directory: .
          run: pnpm install --frozen-lockfile

        - name: Build Next.js
          shell: bash
          working-directory: .
          run: |
            pnpm build
            cp -r .next/static .next/standalone/.next/
            cp -r public .next/standalone/

        - name: Deploy to Static Web App
          id: deploy-to-static-web-app
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN }}
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            action: 'upload'
            app_location: '.'
            output_location: ''
            skip_app_build: true
            skip_api_build: true
            api_location: ''